# Generated by Django 5.1 on 2024-12-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0002_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(max_length=255),
        ),
    ]
