# Generated by Django 5.1 on 2024-12-05 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0007_alter_convite_convidado_alter_convite_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convite',
            name='convidado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.usuario'),
        ),
    ]
